
import { Category, Product } from '../types';

class MockDataManager {
  // FIX: Moved getLogoUrl before products to fix initialization order error.
  private getLogoUrl = (domain: string): string => `https://logo.clearbit.com/${domain}`;

  // Centralized product data with stable IDs and REAL URLs
  private products: Product[] = [
    // Broadband
    { id: 'bt-fibre-2', category: Category.Broadband, provider: 'BT', planName: 'Fibre 2', price: 35.99, logoUrl: this.getLogoUrl('bt.com'), tags: ['Popular'], promotion: '£50 reward card', dealUrl: 'https://www.bt.com/broadband/fibre', features: [{ label: 'Avg. Speed', value: '67 Mbps', highlight: true }, { label: 'Contract', value: '24 months' }, { label: 'Setup cost', value: '£9.99' }] },
    { id: 'sky-superfast', category: Category.Broadband, provider: 'Sky', planName: 'Superfast', price: 34.50, logoUrl: this.getLogoUrl('sky.com'), tags: ['Best Value'], dealUrl: 'https://www.sky.com/broadband', features: [{ label: 'Avg. Speed', value: '59 Mbps', highlight: true }, { label: 'Contract', value: '18 months' }, { label: 'Setup cost', value: '£19.95' }] },
    { id: 'virgin-m500', category: Category.Broadband, provider: 'Virgin Media', planName: 'M500 Fibre', price: 45.00, logoUrl: this.getLogoUrl('virginmedia.com'), tags: ['Fastest'], promotion: 'No setup fee', dealUrl: 'https://www.virginmedia.com/broadband', features: [{ label: 'Avg. Speed', value: '516 Mbps', highlight: true }, { label: 'Contract', value: '18 months' }, { label: 'Setup cost', value: 'Free' }] },
    { id: 'talktalk-fibre-65', category: Category.Broadband, provider: 'TalkTalk', planName: 'Fibre 65', price: 29.95, logoUrl: this.getLogoUrl('talktalk.co.uk'), dealUrl: 'https://new.talktalk.co.uk/broadband', features: [{ label: 'Avg. Speed', value: '67 Mbps', highlight: true }, { label: 'Contract', value: '18 months' }, { label: 'Setup cost', value: 'Free' }] },
    { id: 'plusnet-unlimited', category: Category.Broadband, provider: 'Plusnet', planName: 'Unlimited Fibre', price: 26.99, logoUrl: this.getLogoUrl('plus.net'), tags: ['Low Cost'], promotion: '£75 reward card', dealUrl: 'https://www.plus.net/broadband/', features: [{ label: 'Avg. Speed', value: '36 Mbps', highlight: true }, { label: 'Contract', value: '18 months' }, { label: 'Setup cost', value: 'Free' }] },
    { id: 'vodafone-pro2-900', category: Category.Broadband, provider: 'Vodafone', planName: 'Pro II Full Fibre 900', price: 55.00, logoUrl: this.getLogoUrl('vodafone.co.uk'), tags: ['Fastest', 'Reliable'], promotion: 'Apple TV 4K included', dealUrl: 'https://www.vodafone.co.uk/broadband', features: [{ label: 'Avg. Speed', value: '910 Mbps', highlight: true }, { label: 'Contract', value: '24 months' }, { label: 'Setup cost', value: 'Free' }] },
    { id: 'zen-ff-100', category: Category.Broadband, provider: 'Zen Internet', planName: 'Full Fibre 100', price: 32.99, logoUrl: this.getLogoUrl('zen.co.uk'), tags: ['Top Rated'], dealUrl: 'https://www.zen.co.uk/broadband/full-fibre', features: [{ label: 'Avg. Speed', value: '100 Mbps', highlight: true }, { label: 'Contract', value: '12 months' }, { label: 'Setup cost', value: '£19.99' }] },
    { id: 'hyperoptic-hyperfast', category: Category.Broadband, provider: 'Hyperoptic', planName: 'Hyperfast', price: 40.00, logoUrl: this.getLogoUrl('hyperoptic.com'), tags: ['Fastest'], promotion: '3 months free', dealUrl: 'https://www.hyperoptic.com', features: [{ label: 'Avg. Speed', value: '1 Gbps', highlight: true }, { label: 'Contract', value: '24 months' }, { label: 'Setup cost', value: '£29.00' }] },
    { id: 'community-fibre-1gb', category: Category.Broadband, provider: 'Community Fibre', planName: '1 Gbps Fibre', price: 27.00, logoUrl: this.getLogoUrl('communityfibre.co.uk'), tags: ['London Only'], dealUrl: 'https://communityfibre.co.uk/broadband', features: [{ label: 'Avg. Speed', value: '920 Mbps', highlight: true }, { label: 'Contract', value: '24 months' }, { label: 'Setup cost', value: 'Free' }] },
    { id: 'shell-superfast-plus', category: Category.Broadband, provider: 'Shell Energy Broadband', planName: 'Superfast Fibre Plus', price: 25.99, logoUrl: this.getLogoUrl('shellenergy.co.uk'), tags: ['Low Cost'], dealUrl: 'https://www.shellenergy.co.uk/broadband', features: [{ label: 'Avg. Speed', value: '67 Mbps', highlight: true }, { label: 'Contract', value: '18 months' }, { label: 'Setup cost', value: '£4.95' }] },
    { id: 'ee-ff-500', category: Category.Broadband, provider: 'EE', planName: 'Full Fibre 500', price: 44.99, logoUrl: this.getLogoUrl('ee.co.uk'), tags: ['Reliable'], promotion: 'Save £20/month with mobile', dealUrl: 'https://ee.co.uk/broadband/full-fibre', features: [{ label: 'Avg. Speed', value: '500 Mbps', highlight: true }, { label: 'Contract', value: '24 months' }, { label: 'Setup cost', value: 'Free' }] },
    { id: 'now-fab-fibre', category: Category.Broadband, provider: 'NOW Broadband', planName: 'Fab Fibre', price: 23.00, logoUrl: this.getLogoUrl('nowtv.com'), tags: ['No Contract'], dealUrl: 'https://www.nowtv.com/broadband', features: [{ label: 'Avg. Speed', value: '36 Mbps', highlight: true }, { label: 'Contract', value: '1 month' }, { label: 'Setup cost', value: '£5.00' }] },
    { id: 'kcom-lightstream', category: Category.Broadband, provider: 'KCOM', planName: 'Lightstream Full Fibre', price: 39.99, logoUrl: this.getLogoUrl('kcom.com'), tags: ['Hull Only'], dealUrl: 'https://www.kcom.com/home/broadband/', features: [{ label: 'Avg. Speed', value: '300 Mbps', highlight: true }, { label: 'Contract', value: '18 months' }, { label: 'Setup cost', value: '£24.99' }] },
    { id: 'gnetwork-300', category: Category.Broadband, provider: 'G.Network', planName: '300 Mbps Fibre', price: 32.00, logoUrl: this.getLogoUrl('g.network'), tags: ['London Only', 'Symmetrical'], dealUrl: 'https://g.network/broadband', features: [{ label: 'Avg. Speed', value: '300 Mbps', highlight: true }, { label: 'Contract', value: '24 months' }, { label: 'Setup cost', value: 'Free' }] },
    { id: 'cuckoo-100', category: Category.Broadband, provider: 'Cuckoo', planName: '100Mb Fast Plan', price: 29.99, logoUrl: this.getLogoUrl('cuckoo.co'), tags: ['Flexible'], promotion: '1 month free', dealUrl: 'https://www.cuckoo.co/broadband', features: [{ label: 'Avg. Speed', value: '100 Mbps', highlight: true }, { label: 'Contract', value: '12 months' }, { label: 'Setup cost', value: 'Free' }] },
    
    // Energy
    { id: 'octopus-flexible', category: Category.Energy, provider: 'Octopus Energy', planName: 'Flexible Octopus', price: 152.70, logoUrl: this.getLogoUrl('octopus.energy'), tags: ['Popular', 'Green'], promotion: '£50 account credit', dealUrl: 'https://octopus.energy/tariffs/', features: [{ label: 'Tariff Type', value: 'Variable', highlight: true }, { label: 'Exit Fees', value: 'None' }, { label: 'Green Energy', value: '100%' }] },
    { id: 'bg-standard', category: Category.Energy, provider: 'British Gas', planName: 'Standard Variable', price: 155.30, logoUrl: this.getLogoUrl('britishgas.co.uk'), dealUrl: 'https://www.britishgas.co.uk/energy/tariffs.html', features: [{ label: 'Tariff Type', value: 'Variable', highlight: true }, { label: 'Exit Fees', value: 'None' }, { label: 'Customer Service', value: 'UK Based' }] },
    { id: 'eon-next-flex', category: Category.Energy, provider: 'E.ON Next', planName: 'Next Flex', price: 154.00, logoUrl: this.getLogoUrl('eonnext.com'), tags: ['Green'], dealUrl: 'https://www.eonnext.com/tariffs', features: [{ label: 'Tariff Type', value: 'Variable', highlight: true }, { label: 'Exit Fees', value: 'None' }, { label: 'Green Energy', value: '100% Renewable' }] },
    { id: 'ovo-simpler', category: Category.Energy, provider: 'OVO Energy', planName: 'Simpler Energy', price: 153.50, logoUrl: this.getLogoUrl('ovoenergy.com'), dealUrl: 'https://www.ovoenergy.com/energy-plans', features: [{ label: 'Tariff Type', value: 'Variable', highlight: true }, { label: 'Exit Fees', value: 'None' }, { label: 'Green Energy', value: '100% Renewable' }] },
    { id: 'scottish-power-standard', category: Category.Energy, provider: 'Scottish Power', planName: 'Standard Variable', price: 156.10, logoUrl: this.getLogoUrl('scottishpower.co.uk'), dealUrl: 'https://www.scottishpower.co.uk/energy/tariffs', features: [{ label: 'Tariff Type', value: 'Variable', highlight: true }, { label: 'Exit Fees', value: 'None' }, { label: 'App', value: 'Rated 4.5 Stars' }] },
    { id: 'edf-standard', category: Category.Energy, provider: 'EDF Energy', planName: 'Standard (Variable)', price: 155.80, logoUrl: this.getLogoUrl('edfenergy.com'), dealUrl: 'https://www.edfenergy.com/energy-tariffs', features: [{ label: 'Tariff Type', value: 'Variable', highlight: true }, { label: 'Exit Fees', value: 'None' }, { label: 'Energy Source', value: 'Zero Carbon' }] },
    { id: 'utilita-smart', category: Category.Energy, provider: 'Utilita', planName: 'Smart Energy', price: 158.00, logoUrl: this.getLogoUrl('utilita.co.uk'), tags: ['Prepayment'], dealUrl: 'https://utilita.co.uk/energy-tariffs', features: [{ label: 'Tariff Type', value: 'Variable', highlight: true }, { label: 'Focus', value: 'Pay As You Go' }, { label: 'Smart Meter', value: 'Required' }] },
    { id: 'uw-green', category: Category.Energy, provider: 'Utility Warehouse', planName: 'Green Variable', price: 150.50, logoUrl: this.getLogoUrl('uw.co.uk'), tags: ['Multi-service'], promotion: 'Bundle with other services', dealUrl: 'https://uw.co.uk/services/energy', features: [{ label: 'Tariff Type', value: 'Variable', highlight: true }, { label: 'Exit Fees', value: 'None' }, { label: 'Unique', value: 'Single Bill' }] },
    { id: 'so-juniper', category: Category.Energy, provider: 'So Energy', planName: 'So Juniper', price: 153.20, logoUrl: this.getLogoUrl('so.energy'), promotion: 'Fixed for 1 year', dealUrl: 'https://so.energy/fixed-rate-energy-tariffs', features: [{ label: 'Tariff Type', value: 'Fixed', highlight: true }, { label: 'Exit Fees', value: '£75 per fuel' }, { label: 'Customer Service', value: 'Award-winning' }] },
    { id: 'good-energy-green', category: Category.Energy, provider: 'Good Energy', planName: 'Green Variable', price: 160.10, logoUrl: this.getLogoUrl('goodenergy.co.uk'), tags: ['Ethical', 'Green'], dealUrl: 'https://www.goodenergy.co.uk/our-tariffs/', features: [{ label: 'Tariff Type', value: 'Variable', highlight: true }, { label: 'Exit Fees', value: 'None' }, { label: 'Power Source', value: 'Solar, Wind, Hydro' }] },
    { id: 'ecotricity-green', category: Category.Energy, provider: 'Ecotricity', planName: 'Green Electricity', price: 162.50, logoUrl: this.getLogoUrl('ecotricity.co.uk'), tags: ['Vegan', 'Green'], dealUrl: 'https://www.ecotricity.co.uk/for-your-home', features: [{ label: 'Tariff Type', value: 'Variable', highlight: true }, { label: 'Exit Fees', value: 'None' }, { label: 'Unique', value: 'Profits build new renewables' }] },
    
    // Insurance
    { id: 'aviva-car', category: Category.Insurance, provider: 'Aviva', planName: 'Comprehensive Car', price: 45.20, logoUrl: this.getLogoUrl('aviva.co.uk'), dealUrl: 'https://www.aviva.co.uk/insurance/motor/car-insurance/', features: [{ label: 'Coverage', value: 'Comprehensive', highlight: true }, { label: 'Excess', value: '£250' }, { label: 'Windscreen', value: 'Included' }] },
    { id: 'directline-plus', category: Category.Insurance, provider: 'Direct Line', planName: 'Plus Car Insurance', price: 48.90, logoUrl: this.getLogoUrl('directline.com'), tags: ['Popular'], promotion: 'Guaranteed hire car', dealUrl: 'https://www.directline.com/car-cover', features: [{ label: 'Coverage', value: 'Comprehensive', highlight: true }, { label: 'Excess', value: '£300' }, { label: 'Courtesy Car', value: 'Guaranteed' }] },
    { id: 'admiral-car', category: Category.Insurance, provider: 'Admiral', planName: 'Car Insurance', price: 42.50, logoUrl: this.getLogoUrl('admiral.com'), tags: ['Best Value'], dealUrl: 'https://www.admiral.com/car-insurance', features: [{ label: 'Coverage', value: 'Comprehensive', highlight: true }, { label: 'Excess', value: '£350' }, { label: 'Named Drivers', value: 'Up to 3' }] },
    { id: 'lv-car', category: Category.Insurance, provider: 'LV=', planName: 'Car Insurance', price: 44.80, logoUrl: this.getLogoUrl('lv.com'), tags: ['Top Rated'], dealUrl: 'https://www.lv.com/car-insurance', features: [{ label: 'Coverage', value: 'Comprehensive', highlight: true }, { label: 'Excess', value: '£200' }, { label: 'Uninsured Driver', value: 'Promise' }] },
    { id: 'hastings-premier', category: Category.Insurance, provider: 'Hastings Direct', planName: 'Direct Premier', price: 41.50, logoUrl: this.getLogoUrl('hastingsdirect.com'), tags: ['Low Cost'], dealUrl: 'https://www.hastingsdirect.com/car-insurance/', features: [{ label: 'Coverage', value: 'Comprehensive', highlight: true }, { label: 'Excess', value: '£400' }, { label: 'Breakdown', value: 'Optional' }] },
    { id: 'churchill-car', category: Category.Insurance, provider: 'Churchill', planName: 'Comprehensive', price: 47.10, logoUrl: this.getLogoUrl('churchill.com'), dealUrl: 'https://www.churchill.com/car-insurance', features: [{ label: 'Coverage', value: 'Comprehensive', highlight: true }, { label: 'Excess', value: '£250' }, { label: 'New Car', value: 'Replacement' }] },
    { id: 'axa-motor', category: Category.Insurance, provider: 'AXA', planName: 'Motor Insurance', price: 52.00, logoUrl: this.getLogoUrl('axa.co.uk'), dealUrl: 'https://www.axa.co.uk/car-insurance/', features: [{ label: 'Coverage', value: 'Comprehensive', highlight: true }, { label: 'Excess', value: '£300' }, { label: 'Personal Injury', value: 'Enhanced' }] },
    { id: 'saga-plus', category: Category.Insurance, provider: 'Saga', planName: 'Saga Plus', price: 55.00, logoUrl: this.getLogoUrl('saga.co.uk'), tags: ['Over 50s'], promotion: '3-year fixed price', dealUrl: 'https://www.saga.co.uk/insurance/car-insurance', features: [{ label: 'Coverage', value: 'Comprehensive', highlight: true }, { label: 'Excess', value: '£75' }, { label: 'Unique', value: 'No claims discount protection' }] },
    { id: 'tesco-car', category: Category.Insurance, provider: 'Tesco Bank', planName: 'Car Insurance', price: 40.90, logoUrl: this.getLogoUrl('tescobank.com'), tags: ['Low Cost'], promotion: 'Clubcard discount', dealUrl: 'https://www.tescobank.com/car-insurance/', features: [{ label: 'Coverage', value: 'Comprehensive', highlight: true }, { label: 'Excess', value: '£450' }, { label: 'Perks', value: 'Clubcard points' }] },

    // Mobile
    { id: 'ee-150gb', category: Category.Mobile, provider: 'EE', planName: '150GB Plan', price: 25.00, logoUrl: this.getLogoUrl('ee.co.uk'), tags: ['Popular', '5G'], promotion: '6 months Apple Music', dealUrl: 'https://ee.co.uk/mobile/sim-only-deals', features: [{ label: 'Data', value: '150GB 5G', highlight: true }, { label: 'Contract', value: '24 months' }, { label: 'Calls/Texts', value: 'Unlimited' }] },
    { id: 'o2-plus-100gb', category: Category.Mobile, provider: 'O2', planName: 'Plus Plan 100GB', price: 22.00, logoUrl: this.getLogoUrl('o2.co.uk'), dealUrl: 'https://www.o2.co.uk/shop/sim-cards/sim-only-deals', features: [{ label: 'Data', value: '100GB 5G', highlight: true }, { label: 'Contract', value: '24 months' }, { label: 'Extras', value: 'O2 Priority' }] },
    { id: 'voda-red-100gb', category: Category.Mobile, provider: 'Vodafone', planName: 'Red 100GB', price: 23.50, logoUrl: this.getLogoUrl('vodafone.co.uk'), tags: ['5G'], dealUrl: 'https://www.vodafone.co.uk/mobile/best-sim-only-deals', features: [{ label: 'Data', value: '100GB 5G', highlight: true }, { label: 'Contract', value: '24 months' }, { label: 'Roaming', value: '81 Destinations' }] },
    { id: 'three-unlimited', category: Category.Mobile, provider: 'Three', planName: 'Unlimited Data', price: 20.00, logoUrl: this.getLogoUrl('three.co.uk'), tags: ['Best Value'], promotion: 'First 3 months half price', dealUrl: 'https://www.three.co.uk/shop/sim-only', features: [{ label: 'Data', value: 'Unlimited 5G', highlight: true }, { label: 'Contract', value: '12 months' }, { label: 'Hotspot', value: 'Unlimited' }] },
    { id: 'giffgaff-25gb', category: Category.Mobile, provider: 'giffgaff', planName: '25GB Golden Goodybag', price: 10.00, logoUrl: this.getLogoUrl('giffgaff.com'), tags: ['SIM-Only', 'Flexible'], dealUrl: 'https://www.giffgaff.com/sim-only-plans', features: [{ label: 'Data', value: '25GB 5G', highlight: true }, { label: 'Contract', value: '1 month' }, { label: 'Calls/Texts', value: 'Unlimited' }] },
    { id: 'tesco-60gb', category: Category.Mobile, provider: 'Tesco Mobile', planName: '60GB Clubcard Price', price: 15.00, logoUrl: this.getLogoUrl('tescomobile.com'), tags: ['Best Value'], promotion: 'Requires Clubcard', dealUrl: 'https://www.tescomobile.com/shop/sim-only-deals', features: [{ label: 'Data', value: '60GB 5G', highlight: true }, { label: 'Contract', value: '24 months' }, { label: 'Perks', value: 'Clubcard points' }] },
    { id: 'idmobile-100gb', category: Category.Mobile, provider: 'iD Mobile', planName: '100GB 5G Plan', price: 12.00, logoUrl: this.getLogoUrl('idmobile.co.uk'), tags: ['Low Cost'], dealUrl: 'https://www.idmobile.co.uk/sim-only-deals', features: [{ label: 'Data', value: '100GB 5G', highlight: true }, { label: 'Contract', value: '30-day rolling' }, { label: 'Roaming', value: 'Included' }] },
    { id: 'sky-25gb', category: Category.Mobile, provider: 'Sky Mobile', planName: '25GB Plan', price: 14.00, logoUrl: this.getLogoUrl('sky.com'), promotion: 'Data rollover', dealUrl: 'https://www.sky.com/shop/mobile/sim-only-plans', features: [{ label: 'Data', value: '25GB 5G', highlight: true }, { label: 'Contract', value: '12 months' }, { label: 'Unique', value: 'Piggybank' }] },
    { id: 'voxi-30gb', category: Category.Mobile, provider: 'VOXI', planName: '30GB Plan', price: 12.00, logoUrl: this.getLogoUrl('voxi.co.uk'), tags: ['Social Media'], promotion: 'Endless Social Media', dealUrl: 'https://www.voxi.co.uk/plans', features: [{ label: 'Data', value: '30GB 5G', highlight: true }, { label: 'Contract', value: '1 month' }, { label: 'Unique', value: 'Unlimited social data' }] },
    { id: 'smarty-50gb', category: Category.Mobile, provider: 'SMARTY', planName: '50GB Plan', price: 10.00, logoUrl: this.getLogoUrl('smarty.co.uk'), tags: ['Low Cost', 'Flexible'], dealUrl: 'https://smarty.co.uk/plans', features: [{ label: 'Data', value: '50GB 5G', highlight: true }, { label: 'Contract', value: '1 month' }, { label: 'Calls/Texts', value: 'Unlimited' }] },
  
    // Loans
    { id: 'zopa-loan', category: Category.Loans, provider: 'Zopa', planName: 'Personal Loan', price: 7.9, logoUrl: this.getLogoUrl('zopa.com'), tags: ['Low APR'], dealUrl: 'https://www.zopa.com/loans/personal', features: [{ label: 'Rep. APR', value: '7.9%', highlight: true }, { label: 'Loan Amount', value: '£1k - £25k' }, { label: 'Term', value: '1-5 years' }] },
    { id: 'tesco-loan', category: Category.Loans, provider: 'Tesco Bank', planName: 'Personal Loan', price: 6.5, logoUrl: this.getLogoUrl('tescobank.com'), tags: ['Clubcard Price'], promotion: 'Lower rate for Clubcard members', dealUrl: 'https://www.tescobank.com/loans/', features: [{ label: 'Rep. APR', value: '6.5%', highlight: true }, { label: 'Loan Amount', value: '£7.5k - £25k' }, { label: 'Term', value: '1-7 years' }] },
    { id: 'lendable-loan', category: Category.Loans, provider: 'Lendable', planName: 'Personal Loan', price: 9.9, logoUrl: this.getLogoUrl('lendable.co.uk'), tags: ['Fast Decision'], dealUrl: 'https://www.lendable.co.uk/', features: [{ label: 'Rep. APR', value: '9.9%', highlight: true }, { label: 'Loan Amount', value: '£1k - £20k' }, { label: 'Term', value: '1-5 years' }] },
    { id: 'sainsburys-loan', category: Category.Loans, provider: "Sainsbury's Bank", planName: 'Personal Loan', price: 6.4, logoUrl: this.getLogoUrl('sainsburysbank.co.uk'), tags: ['Low APR', 'Nectar Prices'], dealUrl: 'https://www.sainsburysbank.co.uk/loans', features: [{ label: 'Rep. APR', value: '6.4%', highlight: true }, { label: 'Loan Amount', value: '£7.5k - £25k' }, { label: 'Term', value: '2-5 years' }] },
    { id: 'hsbc-loan', category: Category.Loans, provider: 'HSBC', planName: 'Personal Loan', price: 6.9, logoUrl: this.getLogoUrl('hsbc.co.uk'), tags: ['Trusted'], dealUrl: 'https://www.hsbc.co.uk/loans/products/personal-loan/', features: [{ label: 'Rep. APR', value: '6.9%', highlight: true }, { label: 'Loan Amount', value: '£7k - £15k' }, { label: 'Term', value: '1-5 years' }] },

    // Credit Cards
    { id: 'amex-gold', category: Category.CreditCards, provider: 'American Express', planName: 'Preferred Rewards Gold', price: 29.9, logoUrl: this.getLogoUrl('americanexpress.com'), tags: ['Rewards', 'Travel'], promotion: '20,000 points bonus', dealUrl: 'https://www.americanexpress.com/uk/credit-cards/gold-credit-card/', features: [{ label: 'Rep. APR', value: '29.9% (variable)', highlight: true }, { label: 'Annual Fee', value: '£160 (Free first year)' }, { label: 'Perk', value: 'Lounge Access' }] },
    { id: 'barclaycard-rewards', category: Category.CreditCards, provider: 'Barclaycard', planName: 'Rewards Card', price: 28.9, logoUrl: this.getLogoUrl('barclaycard.co.uk'), tags: ['Cashback'], dealUrl: 'https://www.barclaycard.co.uk/personal/credit-cards/rewards', features: [{ label: 'Rep. APR', value: '28.9% (variable)', highlight: true }, { label: 'Annual Fee', value: 'Free' }, { label: 'Perk', value: '0.25% cashback' }] },
    { id: 'virgin-all-round', category: Category.CreditCards, provider: 'Virgin Money', planName: 'All Round Credit Card', price: 25.9, logoUrl: this.getLogoUrl('virginmoney.com'), tags: ['Balance Transfer'], dealUrl: 'https://uk.virginmoney.com/credit-cards/all-round/', features: [{ label: 'Rep. APR', value: '25.9% (variable)', highlight: true }, { label: 'Annual Fee', value: 'Free' }, { label: 'Perk', value: '0% on transfers' }] },
    { id: 'hsbc-purchase-plus', category: Category.CreditCards, provider: 'HSBC', planName: 'Purchase Plus', price: 24.9, logoUrl: this.getLogoUrl('hsbc.co.uk'), dealUrl: 'https://www.hsbc.co.uk/credit-cards/products/purchase-plus/', features: [{ label: 'Rep. APR', value: '24.9% (variable)', highlight: true }, { label: 'Annual Fee', value: 'Free' }, { label: 'Perk', value: '0% on purchases for 20 months' }] },
    { id: 'santander-all-in-one', category: Category.CreditCards, provider: 'Santander', planName: 'All in One', price: 21.9, logoUrl: this.getLogoUrl('santander.co.uk'), tags: ['Cashback'], dealUrl: 'https://www.santander.co.uk/personal/credit-cards/all-in-one-credit-card', features: [{ label: 'Rep. APR', value: '21.9% (variable)', highlight: true }, { label: 'Annual Fee', value: '£3/month' }, { label: 'Perk', value: '0.5% cashback' }] },

    // Current Accounts
    { id: 'monzo-account', category: Category.CurrentAccounts, provider: 'Monzo', planName: 'Current Account', price: 0, logoUrl: this.getLogoUrl('monzo.com'), tags: ['App Based', 'Popular'], dealUrl: 'https://monzo.com/', features: [{ label: 'Monthly Fee', value: 'Free', highlight: true }, { label: 'Overdraft', value: 'Up to 39% EAR' }, { label: 'FSCS Protected', value: 'Yes' }] },
    { id: 'starling-account', category: Category.CurrentAccounts, provider: 'Starling Bank', planName: 'Personal Account', price: 0, logoUrl: this.getLogoUrl('starlingbank.com'), tags: ['App Based', 'Top Rated'], dealUrl: 'https://www.starlingbank.com/current-account/', features: [{ label: 'Monthly Fee', value: 'Free', highlight: true }, { label: 'Foreign Use', value: 'No fees' }, { label: 'FSCS Protected', value: 'Yes' }] },
    { id: 'chase-account', category: Category.CurrentAccounts, provider: 'Chase', planName: 'Current Account', price: 0, logoUrl: this.getLogoUrl('chase.co.uk'), tags: ['Cashback'], promotion: '1% cashback for 12 months', dealUrl: 'https://www.chase.co.uk/gb/en/support/current-account/', features: [{ label: 'Monthly Fee', value: 'Free', highlight: true }, { label: 'Interest', value: '1% AER' }, { label: 'Cashback', value: '1% on spending' }] },
    { id: 'first-direct-1st', category: Category.CurrentAccounts, provider: 'First Direct', planName: '1st Account', price: 0, logoUrl: this.getLogoUrl('firstdirect.com'), tags: ['Switch Bonus'], promotion: '£175 to switch', dealUrl: 'https://www.firstdirect.com/current-accounts/', features: [{ label: 'Monthly Fee', value: 'Free', highlight: true }, { label: 'Switch Offer', value: '£175' }, { label: 'Customer Service', value: 'Award-winning' }] },
    { id: 'nationwide-flexdirect', category: Category.CurrentAccounts, provider: 'Nationwide', planName: 'FlexDirect', price: 0, logoUrl: this.getLogoUrl('nationwide.co.uk'), tags: ['High Interest'], dealUrl: 'https://www.nationwide.co.uk/current-accounts/flexdirect/', features: [{ label: 'Monthly Fee', value: 'Free', highlight: true }, { label: 'In-credit Interest', value: '5% AER for 12 months' }, { label: 'Switch Offer', value: '£200' }] },

    // Mortgages
    { id: 'halifax-2yr-fixed', category: Category.Mortgages, provider: 'Halifax', planName: '2-Year Fixed', price: 4.85, logoUrl: this.getLogoUrl('halifax.co.uk'), tags: ['First Time Buyer'], dealUrl: 'https://www.halifax.co.uk/mortgages/mortgage-rates.html', features: [{ label: 'Initial Rate', value: '4.85%', highlight: true }, { label: 'Max LTV', value: '95%' }, { label: 'Product Fee', value: '£999' }] },
    { id: 'nationwide-5yr-fixed', category: Category.Mortgages, provider: 'Nationwide', planName: '5-Year Fixed', price: 4.49, logoUrl: this.getLogoUrl('nationwide.co.uk'), tags: ['Remortgage'], promotion: '£500 cashback', dealUrl: 'https://www.nationwide.co.uk/mortgages/mortgage-rates/', features: [{ label: 'Initial Rate', value: '4.49%', highlight: true }, { label: 'Max LTV', value: '90%' }, { label: 'Product Fee', value: '£999' }] },
    { id: 'hsbc-uk-5yr-fixed', category: Category.Mortgages, provider: 'HSBC UK', planName: '5-Year Fixed', price: 4.54, logoUrl: this.getLogoUrl('hsbc.co.uk'), dealUrl: 'https://www.hsbc.co.uk/mortgages/our-rates/', features: [{ label: 'Initial Rate', value: '4.54%', highlight: true }, { label: 'Max LTV', value: '85%' }, { label: 'Product Fee', value: '£0' }] },
    { id: 'santander-2yr-tracker', category: Category.Mortgages, provider: 'Santander', planName: '2-Year Tracker', price: 5.19, logoUrl: this.getLogoUrl('santander.co.uk'), tags: ['Tracker'], dealUrl: 'https://www.santander.co.uk/personal/mortgages/our-mortgage-rates', features: [{ label: 'Initial Rate', value: '5.19% (Tracker)', highlight: true }, { label: 'Max LTV', value: '75%' }, { label: 'Product Fee', value: '£999' }] },
    { id: 'barclays-green-5yr', category: Category.Mortgages, provider: 'Barclays', planName: 'Green Home 5-Year', price: 4.39, logoUrl: this.getLogoUrl('barclays.co.uk'), tags: ['Green Mortgage'], promotion: 'For energy efficient homes', dealUrl: 'https://www.barclays.co.uk/mortgages/green-mortgages/', features: [{ label: 'Initial Rate', value: '4.39%', highlight: true }, { label: 'Max LTV', value: '85%' }, { label: 'Product Fee', value: '£899' }] },
  ];

  private applyFluctuation(products: Product[]): Product[] {
    return products.map(product => {
      // Don't fluctuate rates/APRs for financial products, only costs.
      if (product.category === Category.Energy || product.category === Category.Broadband || product.category === Category.Mobile || product.category === Category.Insurance) {
        const fluctuation = 1 + (Math.random() - 0.5) * 0.1; // +/- 5%
        return { ...product, price: product.price * fluctuation };
      }
      return product; // Return financial products without price fluctuation
    });
  }

  public getProductsByCategory(category: Category): Product[] {
    const categoryProducts = this.products.filter(p => p.category === category);
    return this.applyFluctuation(categoryProducts);
  }
  
  public getProductsByIds(ids: string[]): Product[] {
    const foundProducts = ids
      .map(id => this.products.find(p => p.id === id))
      .filter((p): p is Product => p !== undefined);
    // Apply fluctuation to ensure consistency with what the user sees on the catalogue/favorites pages.
    return this.applyFluctuation(foundProducts);
  }

  public getAllProducts(): Product[] {
    // This is used for the Favorites page, where dynamic pricing adds realism.
    return this.applyFluctuation([...this.products]);
  }
}

export const dataService = new MockDataManager();